export const TABLE_CELL_SELECT = 'TABLE_CELL_SELECT'
export const TABLE_CELL_CHANGE = 'TABLE_CELL_CHANGE'
export const TABLE_CELL_EXIT = 'TABLE_CELL_EXIT'
export const TABLE_PASTE = 'TABLE_PASTE'
export const TABLE_ADD_ROW = 'TABLE_ADD_ROW'
export const TABLE_DEL_ROW = 'TABLE_DEL_ROW'

export const DATASET_SET = 'DATASET_SET'
export const DATASET_SET_OPTIONS = 'DATASET_SET_OPTIONS'
export const DATASET_VALIDATE = 'DATASET_VALIDATE'
export const DATASET_CALCULATE_RESULTS = 'DATASET_CALCULATE_RESULTS'

export const SET_UI_STATE = 'SET_UI_STATE'

export const CHOOSE_MODULE = 'CHOOSE_MODULE'
